-- ##### DEFAULT VALUE ##### --

-- Data in table Type_voie --
INSERT INTO Type_voie VALUES(null, "rue");
INSERT INTO Type_voie VALUES(null, "avenue");
INSERT INTO Type_voie VALUES(null, "chemin");
INSERT INTO Type_voie VALUES(null, "boulevard");
INSERT INTO Type_voie VALUES(null, "place");
INSERT INTO Type_voie VALUES(null, "esplanade");
INSERT INTO Type_voie VALUES(null, "impasse");
INSERT INTO Type_voie VALUES(null, "route");
INSERT INTO Type_voie VALUES(null, "allée");
INSERT INTO Type_voie VALUES(null, "square");

-- Data in table Ville --
INSERT INTO Ville VALUES(null,"Paris", 75000);
INSERT INTO Ville VALUES(null,"Marseille", 13000);
INSERT INTO Ville VALUES(null,"Lyon", 69000);
INSERT INTO Ville VALUES(null,"Toulouse", null);
INSERT INTO Ville VALUES(null,"Nice", null);
INSERT INTO Ville VALUES(null,"Nantes", null);
INSERT INTO Ville VALUES(null,"Strasbourg", null);
INSERT INTO Ville VALUES(null,"Montpellier", null);
INSERT INTO Ville VALUES(null,"Bordeaux", null);
INSERT INTO Ville VALUES(null,"Lille", null);
INSERT INTO Ville VALUES(null,"Rennes", null);
INSERT INTO Ville VALUES(null,"Reims", null);
INSERT INTO Ville VALUES(null,"Le Havre", null);
INSERT INTO Ville VALUES(null,"St Etienne", null);
INSERT INTO Ville VALUES(null,"Toulon", null);
INSERT INTO Ville VALUES(null,"Grenoble", null);
INSERT INTO Ville VALUES(null,"Angers", null);
INSERT INTO Ville VALUES(null,"Dijon", null);
INSERT INTO Ville VALUES(null,"Brest", null);
INSERT INTO Ville VALUES(null,"Le Mans", null);
INSERT INTO Ville VALUES(null,"Nîmes", null);
INSERT INTO Ville VALUES(null,"Aix-en-Provence", null);
INSERT INTO Ville VALUES(null,"Clermont-Ferrant", null);
INSERT INTO Ville VALUES(null,"Tours", null);
INSERT INTO Ville VALUES(null,"St Denis", null);
INSERT INTO Ville VALUES(null,"Limoges", null);
INSERT INTO Ville VALUES(null,"Villeurbanne", null);
INSERT INTO Ville VALUES(null,"Amiens", null);
INSERT INTO Ville VALUES(null,"Besançon", null);
INSERT INTO Ville VALUES(null,"Metz", null);
INSERT INTO Ville VALUES(null,"Perpignan", null);
INSERT INTO Ville VALUES(null,"Orléans", null);
INSERT INTO Ville VALUES(null,"Caen", null);
INSERT INTO Ville VALUES(null,"Mulhouse", null);
INSERT INTO Ville VALUES(null,"Boulogne-Billancourt", null);
INSERT INTO Ville VALUES(null,"Rouen", null);
INSERT INTO Ville VALUES(null,"Nancy", null);
INSERT INTO Ville VALUES(null,"Argenteuil", null);
INSERT INTO Ville VALUES(null,"Montreuil", null);
INSERT INTO Ville VALUES(null,"St Paul", null);
INSERT INTO Ville VALUES(null,"St Denis", null);
INSERT INTO Ville VALUES(null,"Roubaix", null);
INSERT INTO Ville VALUES(null,"Avignon", null);
INSERT INTO Ville VALUES(null,"Turoing", null);
INSERT INTO Ville VALUES(null,"Fort-de-France(Martinique)", null);
INSERT INTO Ville VALUES(null,"Poitiers", null);
INSERT INTO Ville VALUES(null,"Nanterre", null);
INSERT INTO Ville VALUES(null,"Créteil", null);
INSERT INTO Ville VALUES(null,"Verseilles", null);
INSERT INTO Ville VALUES(null,"Pau", null);
INSERT INTO Ville VALUES(null,"Courbevoie", null);
INSERT INTO Ville VALUES(null,"Vitry-sur-Seine", null);
INSERT INTO Ville VALUES(null,"Asnieres-sur-Seine", null);
INSERT INTO Ville VALUES(null,"Colombes", null);
INSERT INTO Ville VALUES(null,"Aulnay-sous-Bois", null);
INSERT INTO Ville VALUES(null,"Rueil-Malmaison", null);
INSERT INTO Ville VALUES(null,"Antibes", null);
INSERT INTO Ville VALUES(null,"La Rochelle", null);
INSERT INTO Ville VALUES(null,"St-Maur-des-Fossés", null);
INSERT INTO Ville VALUES(null,"Calais", null);
INSERT INTO Ville VALUES(null,"Champigny-sur-Marne", null);
INSERT INTO Ville VALUES(null,"St Pierre", null);
INSERT INTO Ville VALUES(null,"Aubervilliers", null);
INSERT INTO Ville VALUES(null,"Béziers", null);
INSERT INTO Ville VALUES(null,"Bourges", null);
INSERT INTO Ville VALUES(null,"Cannnes", null);
INSERT INTO Ville VALUES(null,"St Nazaire", null);
INSERT INTO Ville VALUES(null,"Dunkerque", null);
INSERT INTO Ville VALUES(null,"Quimper", null);
INSERT INTO Ville VALUES(null,"Valence", null);
INSERT INTO Ville VALUES(null,"Colmar", null);
INSERT INTO Ville VALUES(null,"Drancy", null);
INSERT INTO Ville VALUES(null,"Mérignac", null);
INSERT INTO Ville VALUES(null,"Ajaccio", null);
INSERT INTO Ville VALUES(null,"Levallois-Perret", null);
INSERT INTO Ville VALUES(null,"Troyes", null);
INSERT INTO Ville VALUES(null,"Les Abymes", null);
INSERT INTO Ville VALUES(null,"Neuilly-sur-Seine", null);
INSERT INTO Ville VALUES(null,"Issy-Les-Moulineaux", null);
INSERT INTO Ville VALUES(null,"Villeneuve-d'Ascq", null);
INSERT INTO Ville VALUES(null,"Noisy-Le-Grand", null);
INSERT INTO Ville VALUES(null,"Antony", null);
INSERT INTO Ville VALUES(null,"Niort", null);
INSERT INTO Ville VALUES(null,"Lorient", null);
INSERT INTO Ville VALUES(null,"La Seyne sur mer", null);
INSERT INTO Ville VALUES(null,"Chambery", null);
INSERT INTO Ville VALUES(null,"Cayenne(Guyane)", null);
INSERT INTO Ville VALUES(null,"St Quentin", null);
INSERT INTO Ville VALUES(null,"Pessac", null);
INSERT INTO Ville VALUES(null,"Sarcelles", null);
INSERT INTO Ville VALUES(null,"Cergy", null);
INSERT INTO Ville VALUES(null,"Clichy", null);
INSERT INTO Ville VALUES(null,"Beauvais", null);
INSERT INTO Ville VALUES(null,"Cholet   ", null);
INSERT INTO Ville VALUES(null,"Hyrès", null);
INSERT INTO Ville VALUES(null,"Vénissieux", null);
INSERT INTO Ville VALUES(null,"Ivry-sur-Seine", null);
INSERT INTO Ville VALUES(null,"Montauban", null);
INSERT INTO Ville VALUES(null,"Vannes", null);
INSERT INTO Ville VALUES(null,"Charleville-Mézières", null);
INSERT INTO Ville VALUES(null,"Pantin", null);
INSERT INTO Ville VALUES(null,"Laval", null);
INSERT INTO Ville VALUES(null,"Maisons-Alfort", null);
INSERT INTO Ville VALUES(null,"Bondy", null);
INSERT INTO Ville VALUES(null,"Evry", null);
INSERT INTO Ville VALUES(null,"Evreux", null);
INSERT INTO Ville VALUES(null,"Arles", null);
INSERT INTO Ville VALUES(null,"Annecy", null);
INSERT INTO Ville VALUES(null,"Fréjus", null);
INSERT INTO Ville VALUES(null,"Fontenay-sous-Bois", null);
INSERT INTO Ville VALUES(null,"Saint-André(Réunion)", null);
INSERT INTO Ville VALUES(null,"Sartouville", null);
INSERT INTO Ville VALUES(null,"Narbonne", null);
INSERT INTO Ville VALUES(null,"Epinay-sur-Seine", null);
INSERT INTO Ville VALUES(null,"Belfort", null);
INSERT INTO Ville VALUES(null,"Brive-la-Gaillarde", null);
INSERT INTO Ville VALUES(null,"Sevran", null);
INSERT INTO Ville VALUES(null,"Saint-Malo", null);
INSERT INTO Ville VALUES(null,"Albi", null);
INSERT INTO Ville VALUES(null,"Clamart", null);
INSERT INTO Ville VALUES(null,"Blois", null);
INSERT INTO Ville VALUES(null,"Meaux", null);
INSERT INTO Ville VALUES(null,"Villejuif", null);
INSERT INTO Ville VALUES(null,"Saint-Louis(Réunion)", null);
INSERT INTO Ville VALUES(null,"Grasse", null);
INSERT INTO Ville VALUES(null,"Chateauroux", null);
INSERT INTO Ville VALUES(null,"La", null);
INSERT INTO Ville VALUES(null,"Chelles", null);
INSERT INTO Ville VALUES(null,"Cagnes-sur-Mer", null);
INSERT INTO Ville VALUES(null,"Le Tampon", null);
INSERT INTO Ville VALUES(null,"Saint-Brieuc", null);
INSERT INTO Ville VALUES(null,"Chalon-sur-Saône", null);
INSERT INTO Ville VALUES(null,"Carcassonne", null);
INSERT INTO Ville VALUES(null,"Bobigny", null);
INSERT INTO Ville VALUES(null,"Vincennes", null);
INSERT INTO Ville VALUES(null,"Chalons-en-Champagne", null);
INSERT INTO Ville VALUES(null,"Martigues", null);
INSERT INTO Ville VALUES(null,"Le Blanc-Mesnil", null);
INSERT INTO Ville VALUES(null,"Tarbes", null);
INSERT INTO Ville VALUES(null,"Bayonne", null);
INSERT INTO Ville VALUES(null,"Meudon", null);
INSERT INTO Ville VALUES(null,"Montrouge", null);
INSERT INTO Ville VALUES(null,"Angouleme", null);
INSERT INTO Ville VALUES(null,"Aubagne", null);
INSERT INTO Ville VALUES(null,"Boulogne-sur-Mer", null);
INSERT INTO Ville VALUES(null,"Castres", null);
INSERT INTO Ville VALUES(null,"Génnevilliers", null);
INSERT INTO Ville VALUES(null,"Saint-Herblain", null);
INSERT INTO Ville VALUES(null,"Suresnes", null);
INSERT INTO Ville VALUES(null,"Bastia", null);
INSERT INTO Ville VALUES(null,"Douai", null);
INSERT INTO Ville VALUES(null,"Compiègne", null);
INSERT INTO Ville VALUES(null,"Sète", null);
INSERT INTO Ville VALUES(null,"Arras", null);
INSERT INTO Ville VALUES(null,"Valenciennes", null);
INSERT INTO Ville VALUES(null,"Saint-Ouen", null);
INSERT INTO Ville VALUES(null,"Puteaux", null);
INSERT INTO Ville VALUES(null,"Wattrelos", null);
INSERT INTO Ville VALUES(null,"Istres", null);
INSERT INTO Ville VALUES(null,"Saint-Germain-en-Laye", null);
INSERT INTO Ville VALUES(null,"Alfortville", null);
INSERT INTO Ville VALUES(null,"Mantes-la-Jolie", null);
INSERT INTO Ville VALUES(null,"Bourg-en-Bresse", null);
INSERT INTO Ville VALUES(null,"Cherbourg", null);
INSERT INTO Ville VALUES(null,"Talence", null);
INSERT INTO Ville VALUES(null,"Le Cannet", null);
INSERT INTO Ville VALUES(null,"Thionville", null);
INSERT INTO Ville VALUES(null,"Caluire-et-Cuire", null);
INSERT INTO Ville VALUES(null,"Livry-Garan", null);
INSERT INTO Ville VALUES(null,"Corbeil-Essonnes", null);
INSERT INTO Ville VALUES(null,"Chartes", null);
INSERT INTO Ville VALUES(null,"Rosny-sous-Bois", null);
INSERT INTO Ville VALUES(null,"Montluçon", null);
INSERT INTO Ville VALUES(null,"Saint-Priest", null);
INSERT INTO Ville VALUES(null,"Arès", null);
INSERT INTO Ville VALUES(null,"Salon-de-Provence", null);
INSERT INTO Ville VALUES(null,"Vaulx-en-Velin", null);
INSERT INTO Ville VALUES(null,"Massy", null);
INSERT INTO Ville VALUES(null,"Nevers", null);
INSERT INTO Ville VALUES(null,"Garges-lès-Gonesse", null);
INSERT INTO Ville VALUES(null,"Auxerre", null);
INSERT INTO Ville VALUES(null,"Marcq-en-Baroeuf", null);
INSERT INTO Ville VALUES(null,"Bron", null);
INSERT INTO Ville VALUES(null,"Bagneux", null);
INSERT INTO Ville VALUES(null,"Gap", null);
INSERT INTO Ville VALUES(null,"Anglet", null);
INSERT INTO Ville VALUES(null,"Noisy-le-Sec", null);
INSERT INTO Ville VALUES(null,"Melun", null);
INSERT INTO Ville VALUES(null,"Rezé", null);
INSERT INTO Ville VALUES(null,"Draguignan", null);
INSERT INTO Ville VALUES(null,"Le Port", null);
INSERT INTO Ville VALUES(null,"Roanne", null);
INSERT INTO Ville VALUES(null,"Vitrolles", null);
INSERT INTO Ville VALUES(null,"Savigny-sur-Orge", null);
INSERT INTO Ville VALUES(null,"La Courneuve", null);
INSERT INTO Ville VALUES(null,"Jouè-lès-Tours", null);
INSERT INTO Ville VALUES(null,"Choisy-le-Roi", null);
INSERT INTO Ville VALUES(null,"Saint-Chamond", null);
INSERT INTO Ville VALUES(null,"Poissy", null);

-- Clients --
INSERT INTO Client VALUES(null,"Dupont", "Jean");
INSERT INTO Client VALUES(null,"Dacosta", "Didier");
INSERT INTO Client VALUES(null,"Lacroix", "Céline");
INSERT INTO Client VALUES(null,"Pince", "Sebastien");
INSERT INTO Client VALUES(null,"Herman", "Christophe");
INSERT INTO Client VALUES(null,"Cyprès", "Renée");
INSERT INTO Client VALUES(null,"Gauthier", "Sandra");

-- Fournisseurs --
INSERT INTO Fournisseur VALUES(null,"Sylvain");
INSERT INTO Fournisseur VALUES(null,"Mollet");
INSERT INTO Fournisseur VALUES(null,"Prince");

-- Adresses --
INSERT INTO Adresse VALUES(null, 12, 1, "Walter Gropius", 1);
INSERT INTO Adresse VALUES(null, 25, 6, "Leon Blum", 2);
INSERT INTO Adresse VALUES(null, 88, 2, "Pasteur", 3);
INSERT INTO Adresse VALUES(null, 6, 4, "de la République", 1);

-- Attribution adresses fournisseurs --
INSERT INTO Livre_depuis VALUES(1, 1);
INSERT INTO Livre_depuis VALUES(2, 2);
INSERT INTO Livre_depuis VALUES(3, 3);

-- Téléphones --
INSERT INTO Telephone VALUES(null, "0100000000");
INSERT INTO Telephone VALUES(null, "0200000000");
INSERT INTO Telephone VALUES(null, "0300000000");
INSERT INTO Telephone VALUES(null, "0400000000");
INSERT INTO Telephone VALUES(null, "0500000000");
INSERT INTO Telephone VALUES(null, "0600000000");

-- Attribution des numéros fournisseurs --
INSERT INTO Fournisseur_joignable VALUES(1, 1);
INSERT INTO Fournisseur_joignable VALUES(1, 2);
INSERT INTO Fournisseur_joignable VALUES(2, 3);
INSERT INTO Fournisseur_joignable VALUES(2, 4);
INSERT INTO Fournisseur_joignable VALUES(3, 5);
INSERT INTO Fournisseur_joignable VALUES(3, 6);

-- Matières premières --
INSERT INTO Matiere_premiere VALUES(null,"Farine", 50);
INSERT INTO Matiere_premiere VALUES(null,"Œufs", 70);
INSERT INTO Matiere_premiere VALUES(null,"Sucre", 45);
INSERT INTO Matiere_premiere VALUES(null,"Levain", 15);
INSERT INTO Matiere_premiere VALUES(null,"Colorant", 0);

-- Vendu par --
INSERT INTO Vendu_par VALUES(1,1, 2.50);
INSERT INTO Vendu_par VALUES(1,2, 2.48);
INSERT INTO Vendu_par VALUES(2,1, 2.70);
INSERT INTO Vendu_par VALUES(2,3, 2.80);
INSERT INTO Vendu_par VALUES(3,1, 3);
INSERT INTO Vendu_par VALUES(4,2, 1.02);
INSERT INTO Vendu_par VALUES(5,3, 0.70);
