.PHONY : all clean

all :
	cd rapport_general && make
	cd rapport_technique && make
	cd manuel_utilisateur && make
clean :
	cd rapport_general && make clean
	cd rapport_technique && make clean
	cd manuel_utilisateur && make clean
